FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y vim git unzip wget curl gnupg2

RUN apt-get install -y openjdk-8-jdk

RUN wget http://scala-lang.org/files/archive/scala-2.12.8.deb \
    && dpkg -i scala-2.12.8.deb 

RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list \
    && curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add \
    && apt-get update \
    && apt-get install sbt 

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash \
    && apt-get install -y nodejs \
    && npm install -g npm@6.8.0

EXPOSE 8000
EXPOSE 9000
EXPOSE 5000
EXPOSE 8888

RUN useradd mkagan
RUN usermod -aG sudo mkagan
RUN echo "mkagan:mkagan" | chpasswd

VOLUME /home/mkagan/project

USER mkagan
WORKDIR /home/mkagan

